---
abstract: 'experimental / perl types'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires:
  Data::Rx: 0.005
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Rx-TypeBundle-Perl
requires:
  Carp: 0
  Data::Rx: 0.005
  Data::Rx::TypeBundle: 0
  Scalar::Util: 0
resources:
  repository: git://git.codesimply.com/Data-Rx-Type-Perl.git
version: 0.004
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::BumpVersionFromGit
      name: BumpVersionFromGit
      version: 0.007
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/@Basic/GatherDir'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/@Basic/PruneCruft'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/@Basic/ManifestSkip'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/@Basic/MetaYAML'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/@Basic/License'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/@Basic/Readme'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/@Basic/ExtraTests'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/@Basic/ExecDir'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/@Basic/ShareDir'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Filter/@Basic/MakeMaker'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/@Basic/Manifest'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/@Basic/TestRelease'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/@Basic/ConfirmRelease'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/@Basic/UploadToCPAN'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@Filter/AutoPrereq'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/@Git/Check'
      version: 1.102380
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/@Git/Commit'
      version: 1.102380
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/@Git/Tag'
      version: 1.102380
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/@Git/Push'
      version: 1.102380
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102340
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102340
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102340
